add stat_svc
84R5/java-explore-with-me pull request #3
Opened 2023-07-01 08:50 UTC by 84R5

2023-07-02 14:29 UTC, 84R5 commented
Показалось собрал, но нет, косяк в сборке...

2023-07-02 18:48 UTC, 84R5 commented
Не пойму, вроде локально работает, а в контейнере не хочет..

2023-07-02 19:42 UTC, 84R5 commented
Что то застрял... На локальной базе работает, а когда база в контейнере нет, и в локальном и на гите. Сервис в контейнере работает с локальной базой нормально.

2023-07-03 20:10 UTC, Donald522 requested changes
Привет!

Все в целом хорошо, оставил пару замечаний

2023-07-03 20:10 UTC, Donald522 commented on ewm-stats-service/server/src/main/java/ru/practicum/repository/HitRepository.java
> +    @Query(" SELECT new ru.practicum.dto.StatsDtoResponse(h.app, h.uri, COUNT(h.ip)) " +
Не хорошо, чтобы репозиторий возвращал dto модель

2023-07-03 20:10 UTC, Donald522 commented on ewm-stats-service/server/src/main/resources/schema.sql
> +    uri         VARCHAR(255)                            NOT NULL,
На uri и timestamp надо добавить индексы

2023-07-04 10:46 UTC, 84R5 commented on ewm-stats-service/server/src/main/resources/schema.sql
> +    uri         VARCHAR(255)                            NOT NULL,
Добавил

2023-07-04 10:47 UTC, 84R5 commented on ewm-stats-service/server/src/main/java/ru/practicum/repository/HitRepository.java
> +    @Query(" SELECT new ru.practicum.dto.StatsDtoResponse(h.app, h.uri, COUNT(h.ip)) " +
Поменял, но не знаю, ты это имел ввиду или нет. Можешь пояснить? =) Как лучше и почему не стоит возвращать dto?

2023-07-04 20:00 UTC, Donald522 approved these changes

2023-07-05 06:03 UTC, merged